In [1]:
from keras.datasets import boston_housing
(X_train,y_train),(X_test,y_test)=boston_housing.load_data()

Using TensorFlow backend.


57344/57026 [==============================] - 0s 9us/step


In [2]:
print(X_train.shape)

(404, 13)


In [3]:
print(X_train[0])

[  1.23247   0.        8.14      0.        0.538     6.142    91.7
   3.9769    4.      307.       21.      396.9      18.72   ]


In [4]:
print(y_train[0])
print(y_train.shape)

15.2
(404,)


In [5]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X_train)
print(X_scaled[0])

[-0.27224633 -0.48361547 -0.43576161 -0.25683275 -0.1652266  -0.1764426
  0.81306188  0.1166983  -0.62624905 -0.59517003  1.14850044  0.44807713
  0.8252202 ]


In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_normalized=scaler.fit_transform(X_train)
print(X_normalized[0])

[0.01378163 0.         0.28152493 0.         0.31481481 0.49980635
 0.91452111 0.29719123 0.13043478 0.22753346 0.89361702 1.
 0.46881898]


In [7]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
data=np.array(['small','medium','small','large','xlarge','large'])
encoder=LabelEncoder()
data_encoded=encoder.fit_transform(data)
print(data_encoded)

[2 1 2 0 3 0]


In [8]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer
data=np.array(['red','blue','orange','white','red','orange','white','red'])
encoder=LabelBinarizer()
data_encoded=encoder.fit_transform(data)
print(data_encoded)

[[0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
